# Generated by Django 6.0.1 on 2026-01-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0006_address_author_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Address Entries"},
        ),
    ]
